name: Apprentice Test

on:
  push:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: jcs090218/setup-emacs@master
        with:
          version: 28.2
      - name: "Run tests"  
        run: ls -la && make test
