name: melpazoid
on:
  push:
    branches:
    - master
    paths-ignore:
    - '**.md'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with: { python-version: 3.9 }
    - name: Install
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install emacs && emacs --version
        git clone https://github.com/riscy/melpazoid.git ~/melpazoid
        pip install ~/melpazoid
    - name: Run
      env:
        LOCAL_REPO: ${{ github.workspace }}
        RECIPE: (apprentice :fetcher github :repo "Sasanidas/Apprentice")
      run: echo $GITHUB_REF && make -C ~/melpazoid
